  type Query {
    posts(order: SortOrder = DESC, first: Int): [Post!] 
    comments(order:SortOrder = DESC, postId:String): [Comment!]
  }

  type Mutation {
    createPost( content: String!): Post! @auth
    addComment( postId: ID!, content: String!): Comment! @auth
  }

  type Subscription {
   postCreated: Post!
  }

  type Post {
    id: ID!   
    content: String!
    author: User!             
    comments(order: SortOrder = ASC, authorId: String): [Comment!]
  }

  type User {
    id: ID!
    nickname: String!
    image: String
    posts: [Post!]!
  }

  type Comment{
    id: ID!
    content: String!
    author: User!
    post: Post!
  }

  enum SortOrder {
    ASC
    DESC
  }

  directive @auth on FIELD_DEFINITION