type Query {
    posts: [Post!]
  }
   type Mutation {
    createPost( userId:ID! , content: String!): Post!
    addComment( userId:ID! ,postId: ID!, content: String!): Comment!
    # addReaction( postId: ID!, type: ReactionType!): Reaction!
  }

  type Post {
    id: ID!   
    content: String!
    author: User!             
    comments: [Comment!]
  }

    type User {
    id: ID!
    nickname: String!
    image: String
    posts: [Post!]!
  }

  type Comment{
    id: ID!
    content: String!
    author: User!
    post: Post!
  }